import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";

import LayoutProvider from "@/app/LayoutProvider";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Tùy chọn trọng lượng
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <LayoutProvider>
          {children}
          <Toaster />
        </LayoutProvider>
      </body>
    </html>
  );
}
